---
- name: reboot machine
  shell: reboot
  async: 1
  poll: 0
  ignore_errors: true
  notify: wait for reboot to finish
  become: true

- name: wait for reboot to finish
  local_action: wait_for host={{ ansible_host }} state=started port=22 delay=50 timeout=120
  become: false
