- platform: mqtt
  name: shelly25
  command_topic: "shellies/shellyswitch25-5DBF69/roller/0/command"
  position_topic: "shellies/shellyswitch25-5DBF69/roller/0/pos"
  set_position_topic: "shellies/shellyswitch25-5DBF69/roller/0/command/pos"
  availability_topic: "shellies/shellyswitch25-5DBF69/online"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
