- platform: "mqtt"
  name: "living_room_temperature"
  state_topic: "zigbee2mqtt/0x00158d0002b55be4"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"
  value_template: "{{ value_json.temperature }}"
- platform: "mqtt"
  name: "living_room_humidity"
  state_topic: "zigbee2mqtt/0x00158d0002b55be4"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
- platform: "mqtt"
  name: "living_room_battery"
  state_topic: "zigbee2mqtt/0x00158d0002b55be4"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:battery-charging-wireless-50"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "suite_temperature"
  state_topic: "zigbee2mqtt/0x00158d00020ecf1e"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"
  value_template: "{{ value_json.temperature }}"
- platform: "mqtt"
  name: "suite_humidity"
  state_topic: "zigbee2mqtt/0x00158d00020ecf1e"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
- platform: "mqtt"
  name: "suite_battery"
  state_topic: "zigbee2mqtt/0x00158d00020ecf1e"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:battery-charging-wireless-50"
  value_template: "{{ value_json.battery }}"

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
