- platform: "mqtt"
  name: "motion_living_room"
  state_topic: "zigbee2mqtt/0x00158d0001d52460"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"

- platform: "mqtt"
  name: "contact_living_room_1"
  state_topic: "zigbee2mqtt/0x00158d00022efd55"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"
