- platform: broadlink
  type: rm_mini
  host: !secret rm_mini_ip
  mac: !secret rm_mini_mac
  timeout: 15
  switches:
    tv:
      friendly_name: "Samsung TV"
      command_on: "JgAYAZWUEjgSOBI4EhMSExITEhMSExI4EjgROREUERQRFBEVEBUQFBE5ERQRFBEUEhISFBITETgSExI4EjgSOBI4EjgROREABgqUlhE4EjgSOBIUERQRExMSEhQROBI4ETkSExITERUSEhEVEBQROREUERQRFBETEhQRExI4EhMSOBE5EjkROBE5ETkTAAYIlZYRORA5EToQFRAUEhMRFBITETkROBM3ExITEhIUERQRFBEUETgTEhIUERQRFBETEhQROREUETgROhE5ETkQORE5EgAGCpOWEjcSOBM3ExMRExITEhMQFhE4EjgROREVEBQRFRAVEBQRFRA5EhMRFBITERQSExEUEjcSExI5ETkSNxI4EjgRORIADQU="
      command_off: "JgAYAZSWETkSNxI4ExISExITEhMSExM3EjgSOBMSEhMSExITEhMRFBI4ERQSExEUERQSExITEjgSExI4EjgROBI4EzcUNhMABgmUlRM3EjgSOBITERQRFBITERQSOBI4ETgSExITExITEhMSExITNxMSEhMSExITEhMTEhM3EhMSOBE5EjgSOBI3EjgTAAYJlZQSOBI4ETkSExEUERQSExEUEjgRORM2EhQRExITExITEhITEjgSExITEhQRExITEhMSOBITETkSOBE5ETkRORE5EQAGCpSVEzcSOBI4EhMSExEUEhMSExE5EjgRORITERQSExITERQRExM3ExISExITExIUERITEjgSFBE4EjgSOBE5EjgRORMADQU="
