- hosts: all
  become: true

  roles:
    - { role: users, tags: [ users ] }
    - { role: firewall, tags: [ firewall ] }
    - { role: os-hardening, tags: [ hardening, os-hardening ] }
    - { role: ssh-hardening, tags: [ hardening, ssh-hardening ] }
    - { role: docker, tags: [ docker ] }
    - { role: pip, tags: [ pip ] }
