- hosts: all
  become: true

  roles:
    - { role: ntp, tags: [ ntp ] }
    - { role: users, tags: [ users ] }
    - { role: firewall, tags: [ firewall ] }
    - { role: os-hardening, tags: [ hardening, os-hardening ] }
    - { role: ssh-hardening, tags: [ hardening, ssh-hardening ] }
    - { role: docker, tags: [ docker ] }
    - { role: pip, tags: [ pip ] }
    - { role: elasticsearch, tags: [ docker, elasticsearch ] }
    - { role: curator, tags: [ docker, curator ] }
    - { role: kibana, tags: [ docker, kibana ] }
    - { role: filebeat, tags: [ docker, filebeat ] }
    - { role: postgres, tags: [ docker, postgres ] }
    - { role: mqtt, tags: [ docker, mqtt ] }
    - { role: homeassistant, tags: [ docker, homeassistant ] }
